### ISSUE TITLE
درود

### ISSUE THREAD

**Issue by ChickensLord8** [erfanmola/HTMHell#3]
سلام.
این پروژه ی جالبی است.
فقط ی پیشنهاد دارم.
میتونید راه حل مشکلاتی که توی سایت شرح دادید رو اضافه کنید؟

**Comment by erfanmola** [comment]
سلام وقت‌بخیر
راه حل هرکدوم از مشکلات، بسته به فریمورک و کتابخانه و معماری هر پروژه می‌تونه متفاوت باشه، برای همین نمی‌شه راهکار جامعی ارائه داد.
